-- +goose Up
ALTER TABLE wallets
    MODIFY COLUMN consumer_balance DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
    MODIFY COLUMN supplier_available DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
    MODIFY COLUMN supplier_frozen DECIMAL(18,6) NOT NULL DEFAULT 0.000000,
    MODIFY COLUMN total_spend DECIMAL(18,6) NOT NULL DEFAULT 0.000000;

ALTER TABLE wallet_transactions
    MODIFY COLUMN amount DECIMAL(18,6) NOT NULL,
    MODIFY COLUMN balance_before DECIMAL(18,6) NOT NULL,
    MODIFY COLUMN balance_after DECIMAL(18,6) NOT NULL;

ALTER TABLE recharges
    MODIFY COLUMN recharge_quota DECIMAL(18,6) NOT NULL;

ALTER TABLE card_keys
    MODIFY COLUMN amount DECIMAL(18,6) NOT NULL;

ALTER TABLE referral_rewards
    MODIFY COLUMN source_amount DECIMAL(18,6) NOT NULL,
    MODIFY COLUMN reward_amount DECIMAL(18,6) NOT NULL;

ALTER TABLE orders
    MODIFY COLUMN pay_amount DECIMAL(18,6) NOT NULL,
    MODIFY COLUMN refund_amount DECIMAL(18,6) NOT NULL DEFAULT 0.000000;

-- +goose Down
ALTER TABLE orders
    MODIFY COLUMN pay_amount DECIMAL(18,2) NOT NULL,
    MODIFY COLUMN refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00;

ALTER TABLE referral_rewards
    MODIFY COLUMN source_amount DECIMAL(18,2) NOT NULL,
    MODIFY COLUMN reward_amount DECIMAL(18,2) NOT NULL;

ALTER TABLE card_keys
    MODIFY COLUMN amount DECIMAL(18,2) NOT NULL;

ALTER TABLE recharges
    MODIFY COLUMN recharge_quota DECIMAL(18,2) NOT NULL;

ALTER TABLE wallet_transactions
    MODIFY COLUMN amount DECIMAL(18,2) NOT NULL,
    MODIFY COLUMN balance_before DECIMAL(18,2) NOT NULL,
    MODIFY COLUMN balance_after DECIMAL(18,2) NOT NULL;

ALTER TABLE wallets
    MODIFY COLUMN consumer_balance DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN supplier_available DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN supplier_frozen DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    MODIFY COLUMN total_spend DECIMAL(18,2) NOT NULL DEFAULT 0.00;
