package app

// Biblical name data is derived from bible-male-names:
// https://github.com/abranhe/bible-male-names
//
// MIT License
//
// Copyright (c) 2018 Abraham Hernandez
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

var biblicalMailboxNames = [...]string{
	"aaron", "abagtha", "abdeel", "abdiel", "abednego", "abia", "abialbon", "abiathar",
	"abidah", "abiel", "abigibeon", "abihu", "abijah", "abimael", "abinadab", "abiram",
	"abshai", "abishua", "abitub", "abner", "abram", "absalom", "achan", "achor",
	"achim", "adaiah", "adam", "addar", "addi", "adiel", "adina", "adlai",
	"adna", "adonibezek", "adonikam", "adoram", "adonizedec", "adriel", "agabus", "agee",
	"agur", "aharah", "ahasai", "ahasbai", "ahaz", "ahban", "ahi", "ahiam",
	"ahiezer", "ahijah", "ahilud", "ahiman", "ahimoth", "ahio", "ahiram", "ahishahar",
	"ahithophel", "ahoah", "ahumai", "ahuzzath", "ajah", "akkub", "alemeth", "aliah",
	"allon", "alphaeus", "alvan", "amalek", "amasa", "amashai", "amaziah", "aminadab",
	"amiel", "ammihur", "amminadib", "ammizabad", "amnon", "amon", "amoz", "amplias",
	"amraphel", "anah", "anak", "anani", "ananias", "anathoth", "andronicus", "aniam",
	"antipas", "anub", "aphiah", "apollos", "aquila", "arad", "aram", "araunah",
	"archelaus", "ard", "areli", "argob", "aridatha", "arieh", "arioch", "aristarchus",
	"armoni", "arni", "arphaxad", "artaxerxes", "arza", "asahel", "asaiah", "asareel",
	"asarelah", "ashbea", "ashchenaz", "asher", "ashur", "asiel", "asnapper", "asriel",
	"asshur", "asshurim", "asyncritus", "athaiah", "athlai", "augustus", "azaniah", "azareel",
	"azaz", "azbuk", "azal", "aziel", "azmaveth", "azriel", "azur", "azzan",
	"baalhanan", "baana", "baaseiah", "bakbakkar", "bakbukiah", "baladan", "balac", "barabbas",
	"barak", "barjesus", "barkos", "barsaba", "bartholomew", "baruch", "bashanhavothjair", "bavvai",
	"bazluth", "bebai", "bechorath", "bedan", "beeliada", "beerah", "bela", "belshazzar",
	"benaiah", "bendekar", "benhadad", "benhanan", "benhur", "benjamin", "benoni", "beor",
	"berachah", "berechiahberachiah", "beri", "berodachbaladan", "besodeiah", "bethlehem", "bethuel", "bezai",
	"bezer", "bidkar", "bigthan", "bigvai", "bilgah", "bilhan", "bimhal", "binnui",
	"birzavith", "biztha", "boanerges", "bocheru", "bukki", "bunah", "buz", "caesar",
	"cain", "caleb", "chanaan", "careah", "carpus", "cephas", "calcol", "chelal",
	"chelub", "chelubai", "chenani", "cheran", "chileab", "chimham", "chushanrishathaim", "cis",
	"clement", "clopas", "colhozeh", "cononiah", "cornelius", "coz", "crispus", "cushi",
	"cyrus", "dalphon", "daniel", "darda", "darkon", "david", "dedan", "delaiah",
	"demetrius", "diblaim", "didymus", "dionysius", "dishan", "dodai", "dodavah", "doeg",
	"ebal", "ebedmelech", "ebiasaph", "eder", "edom", "ehi", "eker", "elah",
	"elam", "eleasah", "eldad", "eleazar", "eli", "eliada", "eliah", "eliakim",
	"elias", "eliasaph", "eliathah", "eliel", "eliezer", "elioenai", "elihu", "elimelech",
	"eliphalet", "eliphaz", "eliseus", "elishah", "elishaphat", "eliud", "elzaphan", "elkanah",
	"elmadan", "elnathan", "elpaal", "eluzai", "elzabad", "enan", "enoch", "enos",
	"epaenetus", "epaphroditus", "ephai", "ephlal", "ephraim", "er", "erastus", "esaias",
	"esau", "eshban", "eshek", "eshtemoh", "esli", "etam", "ethbaal", "ethni",
	"eutychus", "evilmerodach", "ezbon", "ezekiel", "ezar", "ezrah", "felix", "fortunatus",
	"gabbai", "gaddi", "gadi", "gahar", "galal", "gallio", "gamul", "gashmu",
	"gazez", "geber", "gedor", "gemalli", "genubath", "gershom", "geshan", "gether",
	"gibbar", "giddalti", "gideon", "gideoni", "gilead", "ginnetho", "gispa", "gog",
	"gomer", "haahashtari", "hobiah", "habazziniah", "hachaliah", "hadad", "hadarezer", "hadoram",
	"hagabah", "haggai", "haggi", "hakkatan", "koz", "halohesh", "ham", "hammath",
	"hammedatha", "hamor", "hammuel", "hanameel", "hanan", "hanani", "hanniel", "hanoch",
	"happizzez", "harbona", "hareph", "harhas", "harim", "harnepher", "harum", "haruz",
	"hasenuah", "hashabnah", "hashbadana", "hashem", "hashubah", "hasrah", "senaah", "hashupha",
	"hathach", "hatipha", "hattil", "havilah", "hazaiah", "haziel", "heber", "hege",
	"heldai", "heled", "helek", "heli", "helon", "hemdan", "henadad", "heresh",
	"hermes", "herod", "hesed", "hezeki", "hezion", "hezrai", "hezron", "hiddai",
	"hilkiah", "hinnom", "hiram", "hizkijah", "hod", "hodaviah", "hodiah", "hoham",
	"hophni", "hori", "hosea", "hoshaiah", "hotham", "hothir", "hul", "huppah",
	"hurai", "huram", "hushah", "husham", "huz", "ibhar", "ibnijah", "ibsam",
	"ichabod", "iddo", "igdaliah", "ikkesh", "imla", "immer", "imnah", "imri",
	"ir", "irad", "iri", "irnahash", "isaac", "iscariot", "ishbak", "ishbosheth",
	"ishiah", "ishijah", "ishmael", "ismaiah", "ishod", "ispah", "ishuah", "ishui",
	"isui", "ishvi", "jezliah", "israel", "ithai", "ithiel", "ithra", "ithream",
	"izhar", "izrahiah", "izziah", "jaakan", "jaakobah", "jaalah", "jaanai", "jaareoregim",
	"jaresiah", "jaasu", "jaasiel", "jaazaniah", "jaaziel", "jabesh", "jabin", "jacan",
	"jacob", "jadau", "jadon", "jahaziah", "jahdai", "jahdo", "jahmai", "jahziel",
	"jahzerah", "jairus", "jakim", "jalon", "james", "jamlech", "jannai", "japheth",
	"japhlet", "jareb", "jered", "jarib", "jashen", "jashub", "jason", "javan",
	"jeaterai", "jecamiah", "jechoniah", "jedaiah", "jedidiah", "jeezer", "jehdeiah", "jehiah",
	"jehieli", "jehoadah", "jehoahaz", "jehoash", "jehohanan", "jehoiachin", "jehoiakim", "jehonadab",
	"jehonathan", "joram", "jehoshua", "jehozadak", "jehu", "jehubbah", "jucal", "jehush",
	"jeuel", "jekamiah", "jemuel", "jephthae", "jerah", "jeremai", "jeremy", "jeremoth",
	"jeriah", "jeribai", "jeroboam", "jerubbaal", "jesaiah", "jesharelah", "jesher", "jeshohaiah",
	"jeshuah", "jesimiel", "jesus", "jethro", "jetur", "jeuz", "jaazeniah", "jeziel",
	"jezrahiah", "jibsam", "jimnah", "joab", "joanna", "joatham", "jobab", "joed",
	"joelah", "jogli", "john", "joiakim", "jokim", "joktan", "jona", "jonan",
	"jonathan", "jorim", "josaphat", "josech", "joseph", "joshah", "joshaviah", "joshebbasshebeth",
	"joshua", "josiah", "josiphiah", "jozabad", "jozachar", "jubal", "juda", "jude",
	"junia", "jushabhesed", "kadmiel", "kareah", "kedemah", "kelaiah", "kemuel", "kenazkenez",
	"kirjathjearim", "kishi", "kohath", "korah", "kushaiah", "laadan", "lael", "lahmi",
	"lamech", "lapidoth", "lebanah", "lebbaeus", "lehabim", "letushim", "levi", "likhi",
	"loammi", "lotan", "lucius", "ludim", "lucas", "lysias", "maachah", "maadiah",
	"maasai", "maaseiah", "maaz", "machbannai", "machi", "machnadebai", "madmannah", "magog",
	"magpiash", "magbish", "mahalaleel", "maleleel", "mahath", "mahershalalhashbaz", "mahalah", "mahali",
	"mahol", "malachi", "malcam", "malchijah", "malchiram", "melchishua", "mallothi", "mamre",
	"manahath", "manasses", "maoch", "mareshah", "marcus", "mash", "mathusala", "mattan",
	"mattatah", "mattatha", "mattithiah", "matthan", "matthias", "medad", "mehetabel", "mehida",
	"mehujael", "mehunim", "melatiah", "melchisedec", "melea", "melicu", "memucan", "menan",
	"meonothai", "meraiah", "merari", "meremoth", "meribbaal", "mesha", "meshech", "meshelemiah",
	"meshezabel", "meshillemoth", "meshullam", "methushael", "mezahab", "mibhar", "mibzar", "michah",
	"micha", "michaiah", "michri", "madian", "mikloth", "milalai", "mirma", "mishael",
	"mishma", "mispereth", "mizpar", "mizraim", "mnason", "moadiah", "mordecai", "moza",
	"mushi", "naaman", "naashon", "nabal", "nachon", "nadab", "naggai", "nahamani",
	"nahari", "nahath", "nahor", "nahum", "nephish", "nephthalim", "nathan", "nathanmelech",
	"neariah", "nebajoth", "nebat", "nebuchadnezzar", "rezzar", "nebushazban", "necho", "nedabiah",
	"nehum", "nemuel", "ner", "nergalsharezer", "neriah", "nethaneel", "nethaniah", "nicanor",
	"nicolas", "niger", "nimshi", "noah", "nobah", "nogah", "nun", "obadiah",
	"obed", "obil", "oded", "ohad", "oholiab", "omar", "on", "onan",
	"onesiphorus", "ophrah", "oren", "osee", "othni", "ozem", "ozni", "padon",
	"pahathmoab", "pallu", "palti", "paltiel", "parmashta", "parnach", "pharosh", "paruah",
	"paseah", "pashur", "pathrusim", "paul", "pedahel", "pedaiah", "pekahiah", "pelaliah",
	"peleg", "peleth", "peniel", "perez", "pharez", "persis", "pethahiah", "peulthai",
	"phalec", "pharaoh", "pharaohnechoornechoh", "philemon", "philip", "phinehas", "phurah", "put",
	"pua", "phygellus", "pilate", "pileha", "piltai", "piram", "pithon", "poratha",
	"potiphar", "potiphera", "publius", "pul", "pyrrhus", "raamah", "raamiah", "rabmag",
	"rabshakeh", "ragau", "raham", "rekem", "ramiah", "rapha", "raphu", "reaia",
	"rechab", "regemmelech", "rehob", "roboam", "rehum", "remaliah", "rephah", "resheph",
	"reuben", "rezia", "rezon", "ribai", "rinnah", "rohgah", "rosh", "sabta",
	"sabtecha", "sabtechah", "sadoc", "salah", "shealtiel", "salma", "salmah", "samgarnebo",
	"samson", "sanballat", "saraph", "sarsechim", "saul", "sceva", "secundus", "seir",
	"semachiah", "sennacherib", "seorim", "sered", "serug", "sheth", "shaaph", "shabbethai",
	"shadrach", "shagee", "shallum", "shalmai", "shalmaneser", "shamed", "shamgar", "shamir",
	"shammah", "shammoth", "shammuah", "shapham", "shaphat", "sharar", "sherezer", "shashak",
	"shisha", "sheariah", "sheba", "sheber", "shebnah", "shechaniah", "sichem", "sychar",
	"shehariah", "shelemiah", "shelesh", "shelomith", "shem", "shema", "shemaiah", "shamariah",
	"shemer", "shemida", "shemuel", "shephatiah", "shephi", "shephuphan", "sheresh", "sheshan",
	"shethar", "sheva", "shillem", "shilshah", "shimea", "shimei", "shimhi", "shimma",
	"shimrath", "simri", "shimrom", "shinab", "shiphtan", "shitrai", "shobab", "shobai",
	"shobek", "shoham", "shophach", "shuah", "shubael", "shuni", "shuppim", "siaha",
	"sibbechai", "sidon", "sihon", "silvanus", "symeon", "sippai", "sismai", "so",
	"shoco", "sodi", "sopater", "sophereth", "sotai", "stachys", "stephen", "susi",
	"tabeal", "tabrimon", "tahan", "tahrea", "talmai", "tanhumeth", "tarshish", "tartan",
	"tebah", "tehinnah", "tekoa", "telem", "teman", "temeni", "tarah", "teresh",
	"tertullus", "thahash", "tamah", "theophilus", "thomas", "tibni", "tiglathpileser", "tikvah",
	"tilon", "timna", "timon", "timothy", "tirhakah", "tiria", "titus", "tobadonijah",
	"tobijah", "tohu", "tou", "trophimus", "tubalcain", "tyrannus", "uel", "ulla",
	"unno", "urbane", "uri", "urijah", "uriel", "uz", "uzal", "uzzah",
	"uzzia", "uzziel", "vaizatha", "vashni", "zaavan", "zabad", "zabbud", "zabdiel",
	"zaccai", "zaccur", "zachariah", "zacher", "zaham", "zalmon", "zanoah", "zara",
	"zerah", "zatthu", "zebadiah", "zebedee", "zebul", "zabulon", "zecher", "zeeb",
	"zelophehad", "zemira", "zenas", "zepho", "zephon", "zerahiah", "zeri", "zerubbabel",
	"zetham", "zethar", "ziba", "zibia", "zidkijah", "zilthai", "zimmah", "zimri",
	"ziph", "ziphion", "zithri", "zohar", "zophah", "zophar", "zuph", "zuriel",
}
