package domain

import "errors"

// Sentinel domain errors for Core (resource) module.
var (
	ErrResourceNotFound            = errors.New("resource not found")
	ErrInvalidResourceType         = errors.New("invalid resource type")
	ErrInvalidResourceStatus       = errors.New("invalid resource status")
	ErrInvalidResourceFilter       = errors.New("invalid resource filter")
	ErrResourceSelectionTooLarge   = errors.New("resource selection is too large")
	ErrResourceNotPrivate          = errors.New("resource is not private")
	ErrResourceVersionConflict     = errors.New("resource version conflict")
	ErrResourceIdempotencyConflict = errors.New("resource idempotency conflict")
	ErrResourceHasAllocation       = errors.New("resource has an active allocation")
	ErrResourceDependency          = errors.New("resource dependency is temporarily unavailable")
	ErrInvalidResourceCommand      = errors.New("invalid resource command")
	ErrInvalidResourceOwner        = errors.New("invalid resource owner")
	ErrForbiddenResource           = errors.New("forbidden resource access")
	ErrForbiddenPurpose            = errors.New("forbidden resource purpose")
	ErrDuplicateEmail              = errors.New("duplicate email address in resource import")
	ErrDuplicateDomain             = errors.New("domain already exists")
	ErrInvalidImportFormat         = errors.New("invalid import format")
	ErrFileStorageUnavailable      = errors.New("file storage is temporarily unavailable")
	ErrImportQueueUnavailable      = errors.New("resource import queue is temporarily unavailable")
	ErrResourceImportInvalidClaim  = errors.New("resource import claim is no longer valid")
	ErrMailServerNotFound          = errors.New("mail server not found")
	ErrForbiddenMailServer         = errors.New("forbidden mail server access")
	ErrInvalidMailServerStatus     = errors.New("invalid mail server status")
	ErrMailServerOwnerMismatch     = errors.New("mail server owner does not match resource owner")
	ErrInvalidPurpose              = errors.New("invalid purpose, must be not_sale, sale or binding")
	ErrDomainNotFound              = errors.New("domain not found")
	ErrInvalidDomain               = errors.New("invalid domain")
	ErrProjectNotFound             = errors.New("project not found")
	ErrForbiddenProject            = errors.New("forbidden project access")
	ErrInvalidProject              = errors.New("invalid project")
	ErrInvalidProjectStatus        = errors.New("invalid project status")
	ErrDuplicateProject            = errors.New("project already exists")
	ErrInvalidProduct              = errors.New("invalid product")
	ErrInvalidMailRule             = errors.New("invalid mail rule")
)
