// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for ImportStatusResponseStatus.
const (
	Failed     ImportStatusResponseStatus = "failed"
	Imported   ImportStatusResponseStatus = "imported"
	Processing ImportStatusResponseStatus = "processing"
)

// Valid indicates whether the value is a known member of the ImportStatusResponseStatus enum.
func (e ImportStatusResponseStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Imported:
		return true
	case Processing:
		return true
	default:
		return false
	}
}

// Defines values for PermissionPolicyRequestEffect.
const (
	PermissionPolicyRequestEffectAllow PermissionPolicyRequestEffect = "allow"
	PermissionPolicyRequestEffectDeny  PermissionPolicyRequestEffect = "deny"
)

// Valid indicates whether the value is a known member of the PermissionPolicyRequestEffect enum.
func (e PermissionPolicyRequestEffect) Valid() bool {
	switch e {
	case PermissionPolicyRequestEffectAllow:
		return true
	case PermissionPolicyRequestEffectDeny:
		return true
	default:
		return false
	}
}

// Defines values for PermissionPolicyResponseEffect.
const (
	PermissionPolicyResponseEffectAllow PermissionPolicyResponseEffect = "allow"
	PermissionPolicyResponseEffectDeny  PermissionPolicyResponseEffect = "deny"
)

// Valid indicates whether the value is a known member of the PermissionPolicyResponseEffect enum.
func (e PermissionPolicyResponseEffect) Valid() bool {
	switch e {
	case PermissionPolicyResponseEffectAllow:
		return true
	case PermissionPolicyResponseEffectDeny:
		return true
	default:
		return false
	}
}

// Defines values for SupplierApplicationResponseStatus.
const (
	Approved  SupplierApplicationResponseStatus = "approved"
	Canceled  SupplierApplicationResponseStatus = "canceled"
	Rejected  SupplierApplicationResponseStatus = "rejected"
	Reviewing SupplierApplicationResponseStatus = "reviewing"
)

// Valid indicates whether the value is a known member of the SupplierApplicationResponseStatus enum.
func (e SupplierApplicationResponseStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Canceled:
		return true
	case Rejected:
		return true
	case Reviewing:
		return true
	default:
		return false
	}
}

// Defines values for UserResponseRole.
const (
	Admin      UserResponseRole = "admin"
	SuperAdmin UserResponseRole = "super_admin"
	Supplier   UserResponseRole = "supplier"
	User       UserResponseRole = "user"
)

// Valid indicates whether the value is a known member of the UserResponseRole enum.
func (e UserResponseRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case SuperAdmin:
		return true
	case Supplier:
		return true
	case User:
		return true
	default:
		return false
	}
}

// ActivationRequest defines model for ActivationRequest.
type ActivationRequest struct {
	Email    openapi_types.Email `json:"email"`
	Nickname *string             `json:"nickname,omitempty"`
	Password string              `json:"password"`
}

// ActivationResponse defines model for ActivationResponse.
type ActivationResponse struct {
	// Needed Whether the system requires first-time activation
	Needed bool `json:"needed"`
}

// AdminCreateInviteRequest defines model for AdminCreateInviteRequest.
type AdminCreateInviteRequest struct {
	Code     string     `json:"code"`
	Enabled  *bool      `json:"enabled,omitempty"`
	ExpireAt *time.Time `json:"expireAt,omitempty"`
	MaxUse   int        `json:"maxUse"`
}

// AdminRejectSupplierApplicationRequest defines model for AdminRejectSupplierApplicationRequest.
type AdminRejectSupplierApplicationRequest struct {
	ReviewReason string `json:"reviewReason"`
}

// AdminUpdateInviteRequest defines model for AdminUpdateInviteRequest.
type AdminUpdateInviteRequest struct {
	Enabled  *bool      `json:"enabled,omitempty"`
	ExpireAt *time.Time `json:"expireAt,omitempty"`
	MaxUse   *int       `json:"maxUse,omitempty"`
}

// AdminUpdateUserPermissionsRequest defines model for AdminUpdateUserPermissionsRequest.
type AdminUpdateUserPermissionsRequest struct {
	Policies []PermissionPolicyRequest `json:"policies"`
}

// AdminUpdateUserRequest defines model for AdminUpdateUserRequest.
type AdminUpdateUserRequest struct {
	Enabled   *bool `json:"enabled,omitempty"`
	RoleLevel *int  `json:"roleLevel,omitempty"`
}

// AdminUserListResponse defines model for AdminUserListResponse.
type AdminUserListResponse struct {
	Limit  int            `json:"limit"`
	Offset int            `json:"offset"`
	Total  int            `json:"total"`
	Users  []UserResponse `json:"users"`
}

// CaptchaResponse defines model for CaptchaResponse.
type CaptchaResponse struct {
	// CaptchaId Captcha identifier (must be submitted with answer)
	CaptchaId string `json:"captchaId"`

	// Image Base64-encoded PNG data URI of the captcha image
	Image string `json:"image"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	NewPassword string `json:"newPassword"`
	OldPassword string `json:"oldPassword"`
}

// CreateDomainRequest defines model for CreateDomainRequest.
type CreateDomainRequest struct {
	Domain       string `json:"domain"`
	MailServerId int    `json:"mailServerId"`
	Purpose      string `json:"purpose"`
}

// CreateMailServerRequest defines model for CreateMailServerRequest.
type CreateMailServerRequest struct {
	DkimRecord    *string `json:"dkimRecord,omitempty"`
	DmarcRecord   *string `json:"dmarcRecord,omitempty"`
	MxRecord      *string `json:"mxRecord,omitempty"`
	Name          *string `json:"name,omitempty"`
	PtrRecord     *string `json:"ptrRecord,omitempty"`
	ServerAddress string  `json:"serverAddress"`
	SpfRecord     *string `json:"spfRecord,omitempty"`
}

// DomainResourceDetail defines model for DomainResourceDetail.
type DomainResourceDetail struct {
	CreatedAt       time.Time  `json:"createdAt"`
	Domain          string     `json:"domain"`
	Id              int        `json:"id"`
	LastAllocatedAt *time.Time `json:"lastAllocatedAt,omitempty"`
	MailServerId    int        `json:"mailServerId"`
	Purpose         string     `json:"purpose"`
	Status          string     `json:"status"`
}

// EmailCodeRequest defines model for EmailCodeRequest.
type EmailCodeRequest struct {
	CaptchaAnswer string              `json:"captchaAnswer"`
	CaptchaId     string              `json:"captchaId"`
	Email         openapi_types.Email `json:"email"`
}

// Error defines model for Error.
type Error struct {
	// Fields Field-level validation errors (optional)
	Fields *map[string]string `json:"fields,omitempty"`

	// Message Safe business error message for the user
	Message string `json:"message"`

	// RequestId Correlation ID for troubleshooting
	RequestId string `json:"requestId"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// ImportResponse defines model for ImportResponse.
type ImportResponse struct {
	ImportId int `json:"importId"`
	Imported int `json:"imported"`
}

// ImportStatusResponse defines model for ImportStatusResponse.
type ImportStatusResponse struct {
	CreatedAt     time.Time                  `json:"createdAt"`
	ImportId      int                        `json:"importId"`
	Imported      int                        `json:"imported"`
	LastSafeError *string                    `json:"lastSafeError,omitempty"`
	Status        ImportStatusResponseStatus `json:"status"`
	UpdatedAt     time.Time                  `json:"updatedAt"`
}

// ImportStatusResponseStatus defines model for ImportStatusResponse.Status.
type ImportStatusResponseStatus string

// InviteListResponse defines model for InviteListResponse.
type InviteListResponse struct {
	Invites []InviteResponse `json:"invites"`
	Limit   int              `json:"limit"`
	Offset  int              `json:"offset"`
	Total   int              `json:"total"`
}

// InviteResponse defines model for InviteResponse.
type InviteResponse struct {
	Code      string     `json:"code"`
	CreatedAt time.Time  `json:"createdAt"`
	Enabled   bool       `json:"enabled"`
	ExpireAt  *time.Time `json:"expireAt,omitempty"`
	MaxUse    int        `json:"maxUse"`
	UpdatedAt time.Time  `json:"updatedAt"`
	Used      int        `json:"used"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	CaptchaAnswer string              `json:"captchaAnswer"`
	CaptchaId     string              `json:"captchaId"`
	Email         openapi_types.Email `json:"email"`
	Password      string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	User UserResponse `json:"user"`
}

// MailboxItem defines model for MailboxItem.
type MailboxItem struct {
	CreatedAt       time.Time  `json:"createdAt"`
	Email           string     `json:"email"`
	Id              int        `json:"id"`
	LastAllocatedAt *time.Time `json:"lastAllocatedAt,omitempty"`
	Status          string     `json:"status"`
}

// MailboxListResponse defines model for MailboxListResponse.
type MailboxListResponse struct {
	Items  []MailboxItem `json:"items"`
	Limit  int           `json:"limit"`
	Offset int           `json:"offset"`
	Total  int           `json:"total"`
}

// MicrosoftResourceDetail defines model for MicrosoftResourceDetail.
type MicrosoftResourceDetail struct {
	CreatedAt       time.Time  `json:"createdAt"`
	EmailAddress    string     `json:"emailAddress"`
	ForSale         bool       `json:"forSale"`
	Id              int        `json:"id"`
	LastAllocatedAt *time.Time `json:"lastAllocatedAt,omitempty"`
	LastSafeError   *string    `json:"lastSafeError,omitempty"`
	LongLived       bool       `json:"longLived"`
	QualityScore    int        `json:"qualityScore"`
	Status          string     `json:"status"`
}

// PasswordResetCodeRequest defines model for PasswordResetCodeRequest.
type PasswordResetCodeRequest struct {
	CaptchaAnswer string              `json:"captchaAnswer"`
	CaptchaId     string              `json:"captchaId"`
	Email         openapi_types.Email `json:"email"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Code        string              `json:"code"`
	Email       openapi_types.Email `json:"email"`
	NewPassword string              `json:"newPassword"`
}

// PermissionCatalogItemResponse defines model for PermissionCatalogItemResponse.
type PermissionCatalogItemResponse struct {
	Actions  []string `json:"actions"`
	Resource string   `json:"resource"`
}

// PermissionCatalogResponse defines model for PermissionCatalogResponse.
type PermissionCatalogResponse struct {
	Permissions []PermissionCatalogItemResponse `json:"permissions"`
}

// PermissionPolicyRequest defines model for PermissionPolicyRequest.
type PermissionPolicyRequest struct {
	Action   string                        `json:"action"`
	Effect   PermissionPolicyRequestEffect `json:"effect"`
	Resource string                        `json:"resource"`
}

// PermissionPolicyRequestEffect defines model for PermissionPolicyRequest.Effect.
type PermissionPolicyRequestEffect string

// PermissionPolicyResponse defines model for PermissionPolicyResponse.
type PermissionPolicyResponse struct {
	Action   string                         `json:"action"`
	Effect   PermissionPolicyResponseEffect `json:"effect"`
	Resource string                         `json:"resource"`
}

// PermissionPolicyResponseEffect defines model for PermissionPolicyResponse.Effect.
type PermissionPolicyResponseEffect string

// PublishResourcesRequest defines model for PublishResourcesRequest.
type PublishResourcesRequest struct {
	ResourceIds []int `json:"resourceIds"`
}

// PublishResourcesResponse defines model for PublishResourcesResponse.
type PublishResourcesResponse struct {
	Published int `json:"published"`
	Requested int `json:"requested"`
}

// ReadyzResponse defines model for ReadyzResponse.
type ReadyzResponse struct {
	Dependencies map[string]string `json:"dependencies"`
	Status       string            `json:"status"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Code       string              `json:"code"`
	Email      openapi_types.Email `json:"email"`
	InviteCode *string             `json:"inviteCode,omitempty"`
	Nickname   *string             `json:"nickname,omitempty"`
	Password   string              `json:"password"`
}

// ResourceItem defines model for ResourceItem.
type ResourceItem struct {
	CreatedAt time.Time `json:"createdAt"`

	// Domain Domain name (domain resources only)
	Domain *string `json:"domain,omitempty"`

	// Email Email address (Microsoft resources only)
	Email *string `json:"email,omitempty"`

	// ForSale Microsoft resource is available for sale (Microsoft resources only)
	ForSale *bool `json:"forSale,omitempty"`
	Id      int   `json:"id"`

	// LastSafeError Sanitized abnormal diagnostic summary (Microsoft resources only)
	LastSafeError *string `json:"lastSafeError,omitempty"`

	// LongLived Microsoft resource lifetime classification selected during import
	LongLived *bool `json:"longLived,omitempty"`
	OwnerId   int   `json:"ownerId"`

	// Purpose Domain resource purpose (domain resources only, sale/auxiliary)
	Purpose *string `json:"purpose,omitempty"`

	// Status Resource status (e.g., pending/normal/abnormal/disabled, dns_normal/dns_abnormal)
	Status *string `json:"status,omitempty"`
	Type   string  `json:"type"`
}

// ResourceListResponse defines model for ResourceListResponse.
type ResourceListResponse struct {
	Items  []ResourceItem `json:"items"`
	Limit  int            `json:"limit"`
	Offset int            `json:"offset"`
	Total  int            `json:"total"`
}

// ServerCreateResponse defines model for ServerCreateResponse.
type ServerCreateResponse struct {
	CreatedAt     time.Time `json:"createdAt"`
	Id            int       `json:"id"`
	Name          string    `json:"name"`
	ServerAddress string    `json:"serverAddress"`
	Status        string    `json:"status"`
}

// ServerItem defines model for ServerItem.
type ServerItem struct {
	CreatedAt     time.Time `json:"createdAt"`
	Id            int       `json:"id"`
	Name          string    `json:"name"`
	ServerAddress string    `json:"serverAddress"`
	Status        string    `json:"status"`
}

// ServerListResponse defines model for ServerListResponse.
type ServerListResponse struct {
	Items  []ServerItem `json:"items"`
	Limit  int          `json:"limit"`
	Offset int          `json:"offset"`
	Total  int          `json:"total"`
}

// SupplierApplicationCurrentResponse defines model for SupplierApplicationCurrentResponse.
type SupplierApplicationCurrentResponse struct {
	Application *SupplierApplicationResponse `json:"application"`
}

// SupplierApplicationListResponse defines model for SupplierApplicationListResponse.
type SupplierApplicationListResponse struct {
	Applications []SupplierApplicationResponse `json:"applications"`
	Limit        int                           `json:"limit"`
	Offset       int                           `json:"offset"`
	Total        int                           `json:"total"`
}

// SupplierApplicationRequest defines model for SupplierApplicationRequest.
type SupplierApplicationRequest struct {
	Reason string `json:"reason"`
}

// SupplierApplicationResponse defines model for SupplierApplicationResponse.
type SupplierApplicationResponse struct {
	ApplicantUserId int                               `json:"applicantUserId"`
	CreatedAt       time.Time                         `json:"createdAt"`
	Id              int                               `json:"id"`
	Reason          string                            `json:"reason"`
	ReviewReason    string                            `json:"reviewReason"`
	ReviewedAt      *time.Time                        `json:"reviewedAt,omitempty"`
	ReviewedBy      *int                              `json:"reviewedBy,omitempty"`
	Status          SupplierApplicationResponseStatus `json:"status"`
	UpdatedAt       time.Time                         `json:"updatedAt"`
}

// SupplierApplicationResponseStatus defines model for SupplierApplicationResponse.Status.
type SupplierApplicationResponseStatus string

// UserPermissionPoliciesResponse defines model for UserPermissionPoliciesResponse.
type UserPermissionPoliciesResponse struct {
	Policies []PermissionPolicyResponse `json:"policies"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt   time.Time        `json:"createdAt"`
	Email       string           `json:"email"`
	Enabled     bool             `json:"enabled"`
	Id          int              `json:"id"`
	LastLoginAt *time.Time       `json:"lastLoginAt,omitempty"`
	Nickname    string           `json:"nickname"`
	Role        UserResponseRole `json:"role"`

	// RoleLevel Numeric role level: 10=user, 20=supplier, 80=admin, 100=super_admin
	RoleLevel int       `json:"roleLevel"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// UserResponseRole defines model for UserResponse.Role.
type UserResponseRole string

// CsrfToken defines model for CsrfToken.
type CsrfToken = string

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// GetAdminInvitesParams defines parameters for GetAdminInvites.
type GetAdminInvitesParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostAdminInviteParams defines parameters for PostAdminInvite.
type PostAdminInviteParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// PatchAdminInviteParams defines parameters for PatchAdminInvite.
type PatchAdminInviteParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// GetAdminSupplierApplicationsParams defines parameters for GetAdminSupplierApplications.
type GetAdminSupplierApplicationsParams struct {
	Status *string `form:"status,omitempty" json:"status,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostAdminSupplierApplicationApproveParams defines parameters for PostAdminSupplierApplicationApprove.
type PostAdminSupplierApplicationApproveParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// PostAdminSupplierApplicationRejectParams defines parameters for PostAdminSupplierApplicationReject.
type PostAdminSupplierApplicationRejectParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// GetAdminUsersParams defines parameters for GetAdminUsers.
type GetAdminUsersParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PatchAdminUserParams defines parameters for PatchAdminUser.
type PatchAdminUserParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// PutAdminUserPermissionsParams defines parameters for PutAdminUserPermissions.
type PutAdminUserPermissionsParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// PostAdminRevokeSessionsParams defines parameters for PostAdminRevokeSessions.
type PostAdminRevokeSessionsParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// PostDomainParams defines parameters for PostDomain.
type PostDomainParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// GetDomainMailboxesParams defines parameters for GetDomainMailboxes.
type GetDomainMailboxesParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PatchPasswordParams defines parameters for PatchPassword.
type PatchPasswordParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// GetResourcesParams defines parameters for GetResources.
type GetResourcesParams struct {
	Scope  *string `form:"scope,omitempty" json:"scope,omitempty"`
	Type   *string `form:"type,omitempty" json:"type,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostResourceImportMultipartBody defines parameters for PostResourceImport.
type PostResourceImportMultipartBody struct {
	File openapi_types.File `json:"file"`

	// LongLived Whether every resource in this import batch is long-lived
	LongLived bool `json:"longLived"`
}

// PostResourceImportParams defines parameters for PostResourceImport.
type PostResourceImportParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// PostResourcePublishBatchParams defines parameters for PostResourcePublishBatch.
type PostResourcePublishBatchParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// DeleteResourceParams defines parameters for DeleteResource.
type DeleteResourceParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// GetResourceDetail200JSONResponseBody defines parameters for GetResourceDetail.
type GetResourceDetail200JSONResponseBody struct {
	union json.RawMessage
}

// PostResourcePublishParams defines parameters for PostResourcePublish.
type PostResourcePublishParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// PostResourceValidateParams defines parameters for PostResourceValidate.
type PostResourceValidateParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// GetServersParams defines parameters for GetServers.
type GetServersParams struct {
	Scope  *string `form:"scope,omitempty" json:"scope,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostServerParams defines parameters for PostServer.
type PostServerParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// DeleteSessionParams defines parameters for DeleteSession.
type DeleteSessionParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// PostSupplierApplicationParams defines parameters for PostSupplierApplication.
type PostSupplierApplicationParams struct {
	// XCSRFToken CSRF token from the csrf_token SameSite cookie; required for authenticated state-changing requests.
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// PostActivationJSONRequestBody defines body for PostActivation for application/json ContentType.
type PostActivationJSONRequestBody = ActivationRequest

// PostAdminInviteJSONRequestBody defines body for PostAdminInvite for application/json ContentType.
type PostAdminInviteJSONRequestBody = AdminCreateInviteRequest

// PatchAdminInviteJSONRequestBody defines body for PatchAdminInvite for application/json ContentType.
type PatchAdminInviteJSONRequestBody = AdminUpdateInviteRequest

// PostAdminSupplierApplicationRejectJSONRequestBody defines body for PostAdminSupplierApplicationReject for application/json ContentType.
type PostAdminSupplierApplicationRejectJSONRequestBody = AdminRejectSupplierApplicationRequest

// PatchAdminUserJSONRequestBody defines body for PatchAdminUser for application/json ContentType.
type PatchAdminUserJSONRequestBody = AdminUpdateUserRequest

// PutAdminUserPermissionsJSONRequestBody defines body for PutAdminUserPermissions for application/json ContentType.
type PutAdminUserPermissionsJSONRequestBody = AdminUpdateUserPermissionsRequest

// PostDomainJSONRequestBody defines body for PostDomain for application/json ContentType.
type PostDomainJSONRequestBody = CreateDomainRequest

// PostEmailCodeJSONRequestBody defines body for PostEmailCode for application/json ContentType.
type PostEmailCodeJSONRequestBody = EmailCodeRequest

// PatchPasswordJSONRequestBody defines body for PatchPassword for application/json ContentType.
type PatchPasswordJSONRequestBody = ChangePasswordRequest

// PostPasswordResetJSONRequestBody defines body for PostPasswordReset for application/json ContentType.
type PostPasswordResetJSONRequestBody = PasswordResetRequest

// PostPasswordResetRequestJSONRequestBody defines body for PostPasswordResetRequest for application/json ContentType.
type PostPasswordResetRequestJSONRequestBody = PasswordResetCodeRequest

// PostResourceImportMultipartRequestBody defines body for PostResourceImport for multipart/form-data ContentType.
type PostResourceImportMultipartRequestBody PostResourceImportMultipartBody

// PostResourcePublishBatchJSONRequestBody defines body for PostResourcePublishBatch for application/json ContentType.
type PostResourcePublishBatchJSONRequestBody = PublishResourcesRequest

// PostServerJSONRequestBody defines body for PostServer for application/json ContentType.
type PostServerJSONRequestBody = CreateMailServerRequest

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequest

// PostSupplierApplicationJSONRequestBody defines body for PostSupplierApplication for application/json ContentType.
type PostSupplierApplicationJSONRequestBody = SupplierApplicationRequest

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody = RegisterRequest

// AsMicrosoftResourceDetail returns the union data inside the GetResourceDetail200JSONResponseBody as a MicrosoftResourceDetail
func (t GetResourceDetail200JSONResponseBody) AsMicrosoftResourceDetail() (MicrosoftResourceDetail, error) {
	var body MicrosoftResourceDetail
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMicrosoftResourceDetail overwrites any union data inside the GetResourceDetail200JSONResponseBody as the provided MicrosoftResourceDetail
func (t *GetResourceDetail200JSONResponseBody) FromMicrosoftResourceDetail(v MicrosoftResourceDetail) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMicrosoftResourceDetail performs a merge with any union data inside the GetResourceDetail200JSONResponseBody, using the provided MicrosoftResourceDetail
func (t *GetResourceDetail200JSONResponseBody) MergeMicrosoftResourceDetail(v MicrosoftResourceDetail) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDomainResourceDetail returns the union data inside the GetResourceDetail200JSONResponseBody as a DomainResourceDetail
func (t GetResourceDetail200JSONResponseBody) AsDomainResourceDetail() (DomainResourceDetail, error) {
	var body DomainResourceDetail
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDomainResourceDetail overwrites any union data inside the GetResourceDetail200JSONResponseBody as the provided DomainResourceDetail
func (t *GetResourceDetail200JSONResponseBody) FromDomainResourceDetail(v DomainResourceDetail) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDomainResourceDetail performs a merge with any union data inside the GetResourceDetail200JSONResponseBody, using the provided DomainResourceDetail
func (t *GetResourceDetail200JSONResponseBody) MergeDomainResourceDetail(v DomainResourceDetail) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GetResourceDetail200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GetResourceDetail200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	Healthz(c *gin.Context)
	// Readiness probe
	// (GET /readyz)
	Readyz(c *gin.Context)
	// Check if first activation is needed
	// (GET /v1/activation)
	GetActivation(c *gin.Context)
	// Activate system and create first super_admin
	// (POST /v1/activation)
	PostActivation(c *gin.Context)
	// List invites
	// (GET /v1/admin/invites)
	GetAdminInvites(c *gin.Context, params GetAdminInvitesParams)
	// Create invite
	// (POST /v1/admin/invites)
	PostAdminInvite(c *gin.Context, params PostAdminInviteParams)
	// Update invite
	// (PATCH /v1/admin/invites/{code})
	PatchAdminInvite(c *gin.Context, code string, params PatchAdminInviteParams)
	// List IAM permission catalog
	// (GET /v1/admin/permissions)
	GetAdminPermissions(c *gin.Context)
	// List supplier applications
	// (GET /v1/admin/supplier-applications)
	GetAdminSupplierApplications(c *gin.Context, params GetAdminSupplierApplicationsParams)
	// Approve supplier application
	// (POST /v1/admin/supplier-applications/{applicationId}/approve)
	PostAdminSupplierApplicationApprove(c *gin.Context, applicationId int, params PostAdminSupplierApplicationApproveParams)
	// Reject supplier application
	// (POST /v1/admin/supplier-applications/{applicationId}/reject)
	PostAdminSupplierApplicationReject(c *gin.Context, applicationId int, params PostAdminSupplierApplicationRejectParams)
	// List all users (admin only)
	// (GET /v1/admin/users)
	GetAdminUsers(c *gin.Context, params GetAdminUsersParams)
	// Update a user (enable/disable, change role)
	// (PATCH /v1/admin/users/{userId})
	PatchAdminUser(c *gin.Context, userId int, params PatchAdminUserParams)
	// Get a user's permission overrides
	// (GET /v1/admin/users/{userId}/permissions)
	GetAdminUserPermissions(c *gin.Context, userId int)
	// Replace a user's permission overrides
	// (PUT /v1/admin/users/{userId}/permissions)
	PutAdminUserPermissions(c *gin.Context, userId int, params PutAdminUserPermissionsParams)
	// Force logout a user (revoke all sessions)
	// (POST /v1/admin/users/{userId}/sessions/revoke)
	PostAdminRevokeSessions(c *gin.Context, userId int, params PostAdminRevokeSessionsParams)
	// Create a captcha challenge
	// (POST /v1/captchas)
	PostCaptcha(c *gin.Context)
	// Create a domain resource
	// (POST /v1/domains)
	PostDomain(c *gin.Context, params PostDomainParams)
	// List generated mailboxes for a domain resource
	// (GET /v1/domains/{domainId}/mailboxes)
	GetDomainMailboxes(c *gin.Context, domainId int, params GetDomainMailboxesParams)
	// Send an email verification code
	// (POST /v1/email/code)
	PostEmailCode(c *gin.Context)
	// Get current authenticated user profile
	// (GET /v1/me)
	GetMe(c *gin.Context)
	// Change current user's password
	// (PATCH /v1/password)
	PatchPassword(c *gin.Context, params PatchPasswordParams)
	// Reset password with email verification code
	// (POST /v1/password/reset)
	PostPasswordReset(c *gin.Context)
	// Request a password reset verification code
	// (POST /v1/password/reset/request)
	PostPasswordResetRequest(c *gin.Context)
	// Get resource import status
	// (GET /v1/resource-imports/{importId})
	GetResourceImport(c *gin.Context, importId int)
	// List email resources
	// (GET /v1/resources)
	GetResources(c *gin.Context, params GetResourcesParams)
	// Import Microsoft resources from TXT
	// (POST /v1/resources/imports)
	PostResourceImport(c *gin.Context, params PostResourceImportParams)
	// Publish owned Microsoft resources to public supply
	// (POST /v1/resources/publish)
	PostResourcePublishBatch(c *gin.Context, params PostResourcePublishBatchParams)
	// Delete an owned private Microsoft resource
	// (DELETE /v1/resources/{resourceId})
	DeleteResource(c *gin.Context, resourceId int, params DeleteResourceParams)
	// Get resource detail (no credentials)
	// (GET /v1/resources/{resourceId})
	GetResourceDetail(c *gin.Context, resourceId int)
	// Publish an owned Microsoft resource to public supply
	// (POST /v1/resources/{resourceId}/publish)
	PostResourcePublish(c *gin.Context, resourceId int, params PostResourcePublishParams)
	// Request resource validation (not yet implemented)
	// (POST /v1/resources/{resourceId}/validate)
	PostResourceValidate(c *gin.Context, resourceId int, params PostResourceValidateParams)
	// List mail servers
	// (GET /v1/servers)
	GetServers(c *gin.Context, params GetServersParams)
	// Create a mail server
	// (POST /v1/servers)
	PostServer(c *gin.Context, params PostServerParams)
	// Login and create a session
	// (POST /v1/sessions)
	PostLogin(c *gin.Context)
	// Logout and delete current session
	// (DELETE /v1/sessions/current)
	DeleteSession(c *gin.Context, params DeleteSessionParams)
	// Submit current user's supplier application
	// (POST /v1/supplier-applications)
	PostSupplierApplication(c *gin.Context, params PostSupplierApplicationParams)
	// Get current user's latest supplier application
	// (GET /v1/supplier-applications/current)
	GetCurrentSupplierApplication(c *gin.Context)
	// Register a new user
	// (POST /v1/users)
	PostRegister(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Readyz(c)
}

// GetActivation operation middleware
func (siw *ServerInterfaceWrapper) GetActivation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActivation(c)
}

// PostActivation operation middleware
func (siw *ServerInterfaceWrapper) PostActivation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostActivation(c)
}

// GetAdminInvites operation middleware
func (siw *ServerInterfaceWrapper) GetAdminInvites(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminInvitesParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminInvites(c, params)
}

// PostAdminInvite operation middleware
func (siw *ServerInterfaceWrapper) PostAdminInvite(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAdminInviteParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminInvite(c, params)
}

// PatchAdminInvite operation middleware
func (siw *ServerInterfaceWrapper) PatchAdminInvite(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "code" -------------
	var code string

	err = runtime.BindStyledParameterWithOptions("simple", "code", c.Param("code"), &code, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchAdminInviteParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchAdminInvite(c, code, params)
}

// GetAdminPermissions operation middleware
func (siw *ServerInterfaceWrapper) GetAdminPermissions(c *gin.Context) {

	c.Set(string(CookieAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminPermissions(c)
}

// GetAdminSupplierApplications operation middleware
func (siw *ServerInterfaceWrapper) GetAdminSupplierApplications(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminSupplierApplicationsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminSupplierApplications(c, params)
}

// PostAdminSupplierApplicationApprove operation middleware
func (siw *ServerInterfaceWrapper) PostAdminSupplierApplicationApprove(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "applicationId" -------------
	var applicationId int

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", c.Param("applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter applicationId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAdminSupplierApplicationApproveParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminSupplierApplicationApprove(c, applicationId, params)
}

// PostAdminSupplierApplicationReject operation middleware
func (siw *ServerInterfaceWrapper) PostAdminSupplierApplicationReject(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "applicationId" -------------
	var applicationId int

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", c.Param("applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter applicationId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAdminSupplierApplicationRejectParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminSupplierApplicationReject(c, applicationId, params)
}

// GetAdminUsers operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUsers(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminUsersParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminUsers(c, params)
}

// PatchAdminUser operation middleware
func (siw *ServerInterfaceWrapper) PatchAdminUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchAdminUserParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchAdminUser(c, userId, params)
}

// GetAdminUserPermissions operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUserPermissions(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminUserPermissions(c, userId)
}

// PutAdminUserPermissions operation middleware
func (siw *ServerInterfaceWrapper) PutAdminUserPermissions(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PutAdminUserPermissionsParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutAdminUserPermissions(c, userId, params)
}

// PostAdminRevokeSessions operation middleware
func (siw *ServerInterfaceWrapper) PostAdminRevokeSessions(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId int

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAdminRevokeSessionsParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminRevokeSessions(c, userId, params)
}

// PostCaptcha operation middleware
func (siw *ServerInterfaceWrapper) PostCaptcha(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCaptcha(c)
}

// PostDomain operation middleware
func (siw *ServerInterfaceWrapper) PostDomain(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDomainParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostDomain(c, params)
}

// GetDomainMailboxes operation middleware
func (siw *ServerInterfaceWrapper) GetDomainMailboxes(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "domainId" -------------
	var domainId int

	err = runtime.BindStyledParameterWithOptions("simple", "domainId", c.Param("domainId"), &domainId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter domainId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDomainMailboxesParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDomainMailboxes(c, domainId, params)
}

// PostEmailCode operation middleware
func (siw *ServerInterfaceWrapper) PostEmailCode(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostEmailCode(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(string(CookieAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// PatchPassword operation middleware
func (siw *ServerInterfaceWrapper) PatchPassword(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchPasswordParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchPassword(c, params)
}

// PostPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) PostPasswordReset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPasswordReset(c)
}

// PostPasswordResetRequest operation middleware
func (siw *ServerInterfaceWrapper) PostPasswordResetRequest(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPasswordResetRequest(c)
}

// GetResourceImport operation middleware
func (siw *ServerInterfaceWrapper) GetResourceImport(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "importId" -------------
	var importId int

	err = runtime.BindStyledParameterWithOptions("simple", "importId", c.Param("importId"), &importId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter importId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetResourceImport(c, importId)
}

// GetResources operation middleware
func (siw *ServerInterfaceWrapper) GetResources(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetResourcesParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scope", c.Request.URL.Query(), &params.Scope, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", c.Request.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter type: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetResources(c, params)
}

// PostResourceImport operation middleware
func (siw *ServerInterfaceWrapper) PostResourceImport(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostResourceImportParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostResourceImport(c, params)
}

// PostResourcePublishBatch operation middleware
func (siw *ServerInterfaceWrapper) PostResourcePublishBatch(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostResourcePublishBatchParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostResourcePublishBatch(c, params)
}

// DeleteResource operation middleware
func (siw *ServerInterfaceWrapper) DeleteResource(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId int

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", c.Param("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resourceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteResourceParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteResource(c, resourceId, params)
}

// GetResourceDetail operation middleware
func (siw *ServerInterfaceWrapper) GetResourceDetail(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId int

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", c.Param("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resourceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetResourceDetail(c, resourceId)
}

// PostResourcePublish operation middleware
func (siw *ServerInterfaceWrapper) PostResourcePublish(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId int

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", c.Param("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resourceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostResourcePublishParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostResourcePublish(c, resourceId, params)
}

// PostResourceValidate operation middleware
func (siw *ServerInterfaceWrapper) PostResourceValidate(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "resourceId" -------------
	var resourceId int

	err = runtime.BindStyledParameterWithOptions("simple", "resourceId", c.Param("resourceId"), &resourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter resourceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostResourceValidateParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostResourceValidate(c, resourceId, params)
}

// GetServers operation middleware
func (siw *ServerInterfaceWrapper) GetServers(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServersParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scope", c.Request.URL.Query(), &params.Scope, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scope: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetServers(c, params)
}

// PostServer operation middleware
func (siw *ServerInterfaceWrapper) PostServer(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostServerParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostServer(c, params)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogin(c)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteSessionParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteSession(c, params)
}

// PostSupplierApplication operation middleware
func (siw *ServerInterfaceWrapper) PostSupplierApplication(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostSupplierApplicationParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-CSRF-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-CSRF-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-CSRF-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostSupplierApplication(c, params)
}

// GetCurrentSupplierApplication operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentSupplierApplication(c *gin.Context) {

	c.Set(string(CookieAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCurrentSupplierApplication(c)
}

// PostRegister operation middleware
func (siw *ServerInterfaceWrapper) PostRegister(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostRegister(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/readyz", wrapper.Readyz)
	router.GET(options.BaseURL+"/v1/activation", wrapper.GetActivation)
	router.POST(options.BaseURL+"/v1/activation", wrapper.PostActivation)
	router.GET(options.BaseURL+"/v1/admin/invites", wrapper.GetAdminInvites)
	router.POST(options.BaseURL+"/v1/admin/invites", wrapper.PostAdminInvite)
	router.PATCH(options.BaseURL+"/v1/admin/invites/:code", wrapper.PatchAdminInvite)
	router.GET(options.BaseURL+"/v1/admin/permissions", wrapper.GetAdminPermissions)
	router.GET(options.BaseURL+"/v1/admin/supplier-applications", wrapper.GetAdminSupplierApplications)
	router.POST(options.BaseURL+"/v1/admin/supplier-applications/:applicationId/approve", wrapper.PostAdminSupplierApplicationApprove)
	router.POST(options.BaseURL+"/v1/admin/supplier-applications/:applicationId/reject", wrapper.PostAdminSupplierApplicationReject)
	router.GET(options.BaseURL+"/v1/admin/users", wrapper.GetAdminUsers)
	router.PATCH(options.BaseURL+"/v1/admin/users/:userId", wrapper.PatchAdminUser)
	router.GET(options.BaseURL+"/v1/admin/users/:userId/permissions", wrapper.GetAdminUserPermissions)
	router.PUT(options.BaseURL+"/v1/admin/users/:userId/permissions", wrapper.PutAdminUserPermissions)
	router.POST(options.BaseURL+"/v1/admin/users/:userId/sessions/revoke", wrapper.PostAdminRevokeSessions)
	router.POST(options.BaseURL+"/v1/captchas", wrapper.PostCaptcha)
	router.POST(options.BaseURL+"/v1/domains", wrapper.PostDomain)
	router.GET(options.BaseURL+"/v1/domains/:domainId/mailboxes", wrapper.GetDomainMailboxes)
	router.POST(options.BaseURL+"/v1/email/code", wrapper.PostEmailCode)
	router.GET(options.BaseURL+"/v1/me", wrapper.GetMe)
	router.PATCH(options.BaseURL+"/v1/password", wrapper.PatchPassword)
	router.POST(options.BaseURL+"/v1/password/reset", wrapper.PostPasswordReset)
	router.POST(options.BaseURL+"/v1/password/reset/request", wrapper.PostPasswordResetRequest)
	router.GET(options.BaseURL+"/v1/resource-imports/:importId", wrapper.GetResourceImport)
	router.GET(options.BaseURL+"/v1/resources", wrapper.GetResources)
	router.POST(options.BaseURL+"/v1/resources/imports", wrapper.PostResourceImport)
	router.POST(options.BaseURL+"/v1/resources/publish", wrapper.PostResourcePublishBatch)
	router.DELETE(options.BaseURL+"/v1/resources/:resourceId", wrapper.DeleteResource)
	router.GET(options.BaseURL+"/v1/resources/:resourceId", wrapper.GetResourceDetail)
	router.POST(options.BaseURL+"/v1/resources/:resourceId/publish", wrapper.PostResourcePublish)
	router.POST(options.BaseURL+"/v1/resources/:resourceId/validate", wrapper.PostResourceValidate)
	router.GET(options.BaseURL+"/v1/servers", wrapper.GetServers)
	router.POST(options.BaseURL+"/v1/servers", wrapper.PostServer)
	router.POST(options.BaseURL+"/v1/sessions", wrapper.PostLogin)
	router.DELETE(options.BaseURL+"/v1/sessions/current", wrapper.DeleteSession)
	router.POST(options.BaseURL+"/v1/supplier-applications", wrapper.PostSupplierApplication)
	router.GET(options.BaseURL+"/v1/supplier-applications/current", wrapper.GetCurrentSupplierApplication)
	router.POST(options.BaseURL+"/v1/users", wrapper.PostRegister)
}
